services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Load DATABASE_URL from .env
      - CORS_ORIGINS=${CORS_ORIGINS}  # Load CORS_ORIGINS from .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    # Read from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Read from .env
      POSTGRES_DB: ${POSTGRES_DB}  # Read from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  postgres_data:
